### ISSUE TITLE
If feasible can we consider using Codespaces?

### ISSUE THREAD

**Issue by danielstocker** [microsoft/TechExcel-Integrating-Azure-PaaS-and-AI-Services-for-AI-Design-Wins#6]
https://microsoft.github.io/TechExcel-Integrating-Azure-PaaS-and-AI-Services-for-AI-Design-Wins/docs/01_deploy_app_resources/0101.html

Lists a number of tools to install. Is it feasible to instead provide a Codespace with these pre-requisites so that attendees can save time in this step?

**Comment by feaselkl** [comment]
Codespaces instructions added.
